plugins {
    id 'java'
    id 'jacoco'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.3'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport // Report immer nach den Tests erzeugen
}

jacoco {
    toolVersion = "0.8.14"
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required.set(true)  // XML: wird von den Coverage-Workflows ausgelesen
        html.required.set(true) // HTML: menschlich lesbarer Report
    }
}
