name: CI/CD

on:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/sergiomasegosa11/tictactoe-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Test
        run: ./gradlew clean test